#macro FRAME_RATE 60

enum OPZIONIPAUSA {CONTINUA,RICOMINCIA,IMPOSTAZIONI,ESCI}

enum IMPOST {MUSICA,SFX,DURATA,FATTO}

enum MENUINIZIALE {GIOCA,/*HOWTOPLAY,RECORD,//LISTANOMI,*/IMPOSTAZIONI,RICONOSCIMENTI,ESCI}